name: fbla_mobile_2425_learning_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_3d_controller: ^2.1.0
  firebase_core: ^3.9.0
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.6+1
  flutter_tex: ^4.0.13
  flutter_math_fork: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tinker.obj
    - assets/test_sphere.obj
    - assets/test_sphere.mtl
    - assets/earth_basic_test.glb
    - assets/lvl_test/tinker.obj
    - assets/lvl_test/tinker.mtl
    - assets/streak_homepage_design.png
    - assets/cypher_phrases.txt
    - assets/content.json