name: fbla_mobile_2425_learning_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.6+1
  flutter_tex: ^4.0.13
  flutter_math_fork: ^0.7.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  percent_indicator: ^4.2.4
  flutter_web_auth: ^0.5.0
  dash_chat_2: ^0.0.21
  uuid: ^4.2.2
  flutter_svg: ^2.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/tinker.obj
    - assets/test_sphere.obj
    - assets/test_sphere.mtl
    - assets/earth_basic_test.glb
    - assets/lvl_test/tinker.obj
    - assets/lvl_test/tinker.mtl
    - assets/streak_homepage_design.png
    - assets/cypher_phrases.txt
    - assets/content.json
    - assets/cherry.png
    - assets/mushroom.png
    - assets/earths/1.svg
    - assets/earths/2.svg
    - assets/earths/3.svg
    - assets/earths/4.svg
    - assets/earths/5.svg
    - assets/branding/logo.svg
    - assets/branding/logo_and_name.svg
    - assets/branding/name.svg
    - assets/homepage_design/left.svg
    - assets/homepage_design/right.svg
